### ISSUE TITLE
Format on save

### ISSUE THREAD

**Issue by hasanbayatme** [akof1314/Sublime-CoolFormat#10]
How do i foramt on save?

**Comment by akof1314** [comment]
With the help of the plugin sublime-hooks  （https://github.com/twolfson/sublime-hooks）

ex. JSON 
via Preferences -> Settings - More -> Syntax Specific - User in the menu.
```
{
	"on_pre_save_language": [
    {
      "command": "coolformat",
      "args": { "action": "quickFormat" }
    }
  ]
}
```

**Comment by hasanbayatme** [comment]
Thanks. that's nice.

Please add it to the `README.md` file for others to know.
Also try to make a option for sublime-coolformat.

Thanks.
All the bests.
