### ISSUE TITLE
Ctrl+shift+alt+q后会删除文件代码，ctrl+shift+alt+s会删除指定行

### ISSUE THREAD

**Issue by Whisht** [akof1314/Sublime-CoolFormat#4]
![qq 20160308194852](https://cloud.githubusercontent.com/assets/16497652/13601035/02b5feaa-e568-11e5-9cee-ae071eef2672.png)   格式化前
![qq 20160308194859](https://cloud.githubusercontent.com/assets/16497652/13601036/02bd44d0-e568-11e5-908b-4e2efbc027d7.png)
    格式化后  
原因是C improved插件安装造成的，望修复

**Comment by akof1314** [comment]
快捷键冲突了，可以手动改下快捷键隐射配置文件。

**Comment by youth7** [comment]
我也是装了c improve，请问要修改哪些配置啊？

**Comment by akof1314** [comment]
@youth7 更改Default.sublime-keymap文件

**Comment by owl-lwo** [comment]
找不到Default.sublime-keymap文件
