### ISSUE TITLE
请问在 C++ 格式化时如何指定在函数之间加上空行？

### ISSUE THREAD

**Issue by piratf** [akof1314/Sublime-CoolFormat#6]
我阅读了 doc 文档，目前的 SynTidy 是：
C++=""-A14-xn-xc-xl-xk-s-C-xG-S-K-p-N-xW-w-Y-f-H-k3-j-xC""

我想在函数之间也强制加上空行。

**Comment by akof1314** [comment]
暂时不能在函数之间加空行。

**Comment by piratf** [comment]
感谢回复，这个插件非常棒，我非常喜欢！谢谢你
